// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfWPbIlrQU-8toLYkE3hDxiawA-HqrhMU',
    appId: '1:477084001615:web:beb812da7a30641fc5d13a',
    messagingSenderId: '477084001615',
    projectId: 'react-d3fd5',
    authDomain: 'react-d3fd5.firebaseapp.com',
    databaseURL: 'https://react-d3fd5-default-rtdb.firebaseio.com',
    storageBucket: 'react-d3fd5.appspot.com',
    measurementId: 'G-FHQ4HQWSXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhL7svcSs5Xk1zJrb_Sd6_QKtl-P7LuJA',
    appId: '1:477084001615:android:1e8fb04cbae6e37ac5d13a',
    messagingSenderId: '477084001615',
    projectId: 'react-d3fd5',
    databaseURL: 'https://react-d3fd5-default-rtdb.firebaseio.com',
    storageBucket: 'react-d3fd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb10tFk1VTETwtAeChtZE_9yhu6DmZKxs',
    appId: '1:477084001615:ios:d8be5af9cdd497e7c5d13a',
    messagingSenderId: '477084001615',
    projectId: 'react-d3fd5',
    databaseURL: 'https://react-d3fd5-default-rtdb.firebaseio.com',
    storageBucket: 'react-d3fd5.appspot.com',
    iosBundleId: 'com.example.eventOrganiser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb10tFk1VTETwtAeChtZE_9yhu6DmZKxs',
    appId: '1:477084001615:ios:d8be5af9cdd497e7c5d13a',
    messagingSenderId: '477084001615',
    projectId: 'react-d3fd5',
    databaseURL: 'https://react-d3fd5-default-rtdb.firebaseio.com',
    storageBucket: 'react-d3fd5.appspot.com',
    iosBundleId: 'com.example.eventOrganiser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfWPbIlrQU-8toLYkE3hDxiawA-HqrhMU',
    appId: '1:477084001615:web:40158f0596e2911bc5d13a',
    messagingSenderId: '477084001615',
    projectId: 'react-d3fd5',
    authDomain: 'react-d3fd5.firebaseapp.com',
    databaseURL: 'https://react-d3fd5-default-rtdb.firebaseio.com',
    storageBucket: 'react-d3fd5.appspot.com',
    measurementId: 'G-24B79G7D2W',
  );

}